### PR TITLE
update deps

### LINKED ISSUE #739: Cargo Udeps
# Unused dependencies 
| Crate | Package | Type |
|----:|-------:|-------:|
|anoma_apps 0.6.1|curl|normal|
|anoma_apps 0.6.1|pathdiff|normal|
|anoma_apps 0.6.1|winapi|normal|

### PR DESCRIPTION
**Pull request by tzemanovic**
based on #751 to avoid conflicts

also closes #739

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763137186563) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by tzemanovic** [comment]
pls update wasm

**Review by Fraccaman — APPROVED** [review]

**Comment by juped** [comment]
needs resolution after #751

**Comment by tzemanovic** [comment]
let's rebase it after v0.6.0 and update more deps

**Comment by tzemanovic** [comment]
let's rebase it after v0.6.0 and update more deps

**Pull request closed without merging**
