### PR TITLE
update libp2p

### LINKED ISSUE #340: upgrade libp2p version
Upgrade libp2p to the latest version. The current 0.38.0 is affected by https://rustsec.org/advisories/RUSTSEC-2021-0073.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763008328209) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by tzemanovic**
closes #340

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763136695273) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by Fraccaman — APPROVED** [review]

**Comment by juped** [comment]
needs resolution

**Comment by juped** [comment]
tests seem to hang. i rebased this forward past the tests-fixing branches

**Comment by juped** [comment]
cancelled ci because of stuck tests

**Comment by tzemanovic** [comment]
@juped thanks! I'll take a look

**Comment by tzemanovic** [comment]
it's quite strange, I can reproduce it getting stuck locally, but the command it gets stuck on is:

```
cargo build --message-format=json --package anoma_apps --manifest-path anoma/Cargo.toml --features ABCI --bin anomac --release
```

which by itself does have issues

**Comment by tzemanovic** [comment]
on another try locally, it got stuck on building anoman :/ CI 2nd try passed though

**Comment by juped** [comment]
converting to draft just because it's broken for now

**Comment by tzemanovic** [comment]
this is currently blocked, but not a priority as it's only used in intent gossiper

**Pull request closed without merging**
